version: '3.7'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: poc-spring-reactive-timescale
      POSTGRES_HOST_AUTH_METHOD: trust
