spring:
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/poc-spring-reactive-timescale
    username: postgres
    password: root

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE